In [3]:
import pandas as pd

#팀원이 전처리 해둔 데이터인 scaled.csv를 그대로 사용
#Time, Amount를 minmaxScaler로 [-1,1]로 스케일링
#결측치가 존재하지 않는 데이터이므로 스케일링만 적용함

df = pd.read_csv('scaled.csv')
print(f"[INFO] Dataset loaded successfully. Shape: {df.info()}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB
[INFO] Dataset loaded successfully. Shape: None

In [4]:
from sklearn.model_selection import train_test_split

X = df.drop('Class', axis=1)
y = df['Class']

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.4, stratify=y, random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42
)

In [5]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_smote_train, y_smote_train = smote.fit_resample(X_train, y_train)

c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\backend\context.py:131: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] 지정된 파일을 찾을 수 없습니다
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\backend\context.py", line 247, in _count_physical_cores
    cpu_count_physical = _count_physical_cores_win32()
  File "c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\site-packages\joblib\externals\loky\backend\context.py", line 299, in _count_physical_cores_win32
    cpu_info = subprocess.run(
  File "c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\yeon\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

In [6]:
X_smote_train.info()
y_smote_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 341178 entries, 0 to 341177
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    341178 non-null  float64
 1   V1      341178 non-null  float64
 2   V2      341178 non-null  float64
 3   V3      341178 non-null  float64
 4   V4      341178 non-null  float64
 5   V5      341178 non-null  float64
 6   V6      341178 non-null  float64
 7   V7      341178 non-null  float64
 8   V8      341178 non-null  float64
 9   V9      341178 non-null  float64
 10  V10     341178 non-null  float64
 11  V11     341178 non-null  float64
 12  V12     341178 non-null  float64
 13  V13     341178 non-null  float64
 14  V14     341178 non-null  float64
 15  V15     341178 non-null  float64
 16  V16     341178 non-null  float64
 17  V17     341178 non-null  float64
 18  V18     341178 non-null  float64
 19  V19     341178 non-null  float64
 20  V20     341178 non-null  float64
 21  V21     341178 non-null  float64
 22  V22     341178 non-null  float64
 23  V23     341178 non-null  float64
 24  V24     341178 non-null  float64
 25  V25     341178 non-null  float64
 26  V26     341178 non-null  float64
 27  V27     341178 non-null  float64
 28  V28     341178 non-null  float64
 29  Amount  341178 non-null  float64
dtypes: float64(30)
memory usage: 78.1 MB
<class 'pandas.core.series.Series'>
RangeIndex: 341178 entries, 0 to 341177
Series name: Class
Non-Null Count   Dtype
--------------   -----
341178 non-null  int64
dtypes: int64(1)
memory usage: 2.6 MB

In [7]:
from sklearn.ensemble import RandomForestClassifier

# 5-1. (X_train, y_train) + class_weight X
rf_naive_train = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf_naive_train.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [8]:
# 5-2. (X_smote_train, y_smote_train) + class_weight X
rf_naive_smote = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)
rf_naive_smote.fit(X_smote_train, y_smote_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [9]:
# 5-3. (X_train,y_train) + class_weight
rf_class_weighted_train = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_class_weighted_train.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [10]:
# 5-4. (X_smote_train, y_smote_train) + class_weight
rf_class_weighted_smote = RandomForestClassifier(
    n_estimators=100,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)
rf_class_weighted_smote.fit(X_smote_train, y_smote_train)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [11]:
from sklearn.metrics import log_loss

models = {
    "5-1 naive train": rf_naive_train,
    "5-2 naive SMOTE": rf_naive_smote,
    "5-3 weighted train": rf_class_weighted_train,
    "5-4 weighted SMOTE": rf_class_weighted_smote
}

for name, model in models.items():
    # Train loss
    y_train_pred_prob = model.predict_proba(X_train)[:, 1]
    train_loss = log_loss(y_train, y_train_pred_prob)

    # Validation loss
    y_val_pred_prob = model.predict_proba(X_val)[:, 1]
    val_loss = log_loss(y_val, y_val_pred_prob)

    print(f"{name} | train loss: {train_loss:.6f} | validation loss: {val_loss:.6f}")

5-1 naive train | train loss: 0.000408 | validation loss: 0.008996
5-2 naive SMOTE | train loss: 0.001200 | validation loss: 0.009859
5-3 weighted train | train loss: 0.000385 | validation loss: 0.008998
5-4 weighted SMOTE | train loss: 0.001200 | validation loss: 0.009859

SMOTE를 적용한 5-2, 5-4 둘 다 SMOTE를 적용하지 않은 케이스에 비해서 loss가 약 10%정도 크게 나타났음을 알 수 있다. 따라서 SMOTE적용은 양성 희소성 해결에 도움이 되지 않고 오히려 악화시켰음을 확인하였다. 다음으로 기본 데이터셋에 class weight를 적용하지 않은 naive_train과 class_weighted_train은 log loss상으로 손실이 비슷하게 나타났고 train loss와 validation loss 값의 비교만으로 과적합인지 판단이 어려움으로 실제 사기 탐지 결과값으로 두 모델 중 어떤 모델이 사기 탐지에 적합할지 확인해봐야 한다.

In [12]:
from sklearn.metrics import precision_score, recall_score, average_precision_score

models = {
    "5-1 naive train": rf_naive_train,
    "5-3 weighted train": rf_class_weighted_train
}

for name, model in models.items():
    y_val_pred = model.predict(X_val)
    y_val_prob = model.predict_proba(X_val)[:, 1]

    prec = precision_score(y_val, y_val_pred)
    rec = recall_score(y_val, y_val_pred)
    auprc = average_precision_score(y_val, y_val_prob)

    print(f"{name} | precision: {prec:.4f} | recall: {rec:.4f} | auprc: {auprc:.4f}")

5-1 naive train | precision: 0.9367 | recall: 0.7551 | auprc: 0.7996
5-3 weighted train | precision: 0.9315 | recall: 0.6939 | auprc: 0.7909

양성 희소성 해결 정책으로 SMOTE와 class_weight를 각각 및 함께 적용해 비교했지만, validation loss와 precision, recall, AUPRC 기준으로 모두 naive 모델이 가장 좋은 성능을 보였으며, 이후 실험은 불균형 처리 없이 진행하기로 결정하였다.
이론적으로는 class_weight가 소수 클래스 탐지에 도움이 될 것으로 예측했지만, 해당 데이터와 randomforest 모델에서는 오히려 성능 저하가 관찰되어 채택하지 않았다.

In [ ]:
from sklearn.metrics import log_loss, precision_score, recall_score, average_precision_score, roc_auc_score


def eval_rf(params, X_train, y_train, X_val, y_val, threshold=0.5, verbose=False):

    model = RandomForestClassifier(
        **params,
        random_state=42,
        n_jobs=-1
    )
    model.fit(X_train, y_train)
    
    # prob, pred
    y_val_prob = model.predict_proba(X_val)[:, 1]
    y_val_pred = (y_val_prob >= threshold).astype(int)
    
    # metrics
    val_loss = log_loss(y_val, y_val_prob)
    prec = precision_score(y_val, y_val_pred, zero_division=0)
    rec = recall_score(y_val, y_val_pred, zero_division=0)
    auprc = average_precision_score(y_val, y_val_prob)
    roc_auc = roc_auc_score(y_val, y_val_prob)
    
    if verbose:
        print(f"params={params}")
        print(f"  val_loss={val_loss:.4f}, precision={prec:.4f}, recall={rec:.4f}, auprc={auprc:.4f}, roc_auc={roc_auc:.4f}")
    
    return {
        "val_log_loss": val_loss,
        "val_precision": prec,
        "val_recall": rec,
        "val_auprc": auprc,
        "val_roc_auc": roc_auc,
        "model": model
    }

In [14]:
base_params = {
    "n_estimators": 100,
    "max_depth": None,
    "min_samples_split": 2,
    "min_samples_leaf": 1,
    "max_features": "sqrt",
}

n_est_candidates = [100, 200, 300]

n_est_results = []

for n in n_est_candidates:
    params = base_params.copy()
    params["n_estimators"] = n
    
    metrics = eval_rf(params, X_train, y_train, X_val, y_val)
    metrics.update(params)
    n_est_results.append(metrics)

n_est_df = pd.DataFrame(n_est_results)
n_est_df = n_est_df.sort_values(by=["val_auprc", "val_recall", "val_precision"], ascending=[False, False, False])
n_est_df

,val_log_loss,val_precision,val_recall,val_auprc,val_roc_auc,model,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features
1,0.009009,0.936709,0.755102,0.802752,0.935856,"(DecisionTreeClassifier(max_features='sqrt', r...",200,None,2,1,sqrt
0,0.008996,0.936709,0.755102,0.799594,0.936899,"(DecisionTreeClassifier(max_features='sqrt', r...",100,None,2,1,sqrt
2,0.009026,0.936709,0.755102,0.798353,0.934988,"(DecisionTreeClassifier(max_features='sqrt', r...",300,None,2,1,sqrt

In [15]:
best_n = int(n_est_df.iloc[0]["n_estimators"])
print("BEST n_estimators:", best_n)

base_params["n_estimators"] = best_n

BEST n_estimators: 200

In [16]:
depth_candidates = [None, 10, 15, 20]

depth_results = []

for depth in depth_candidates:
    params = base_params.copy()
    params["max_depth"] = depth
    
    metrics = eval_rf(params, X_train, y_train, X_val, y_val)
    metrics.update(params)
    depth_results.append(metrics)

depth_df = pd.DataFrame(depth_results)
depth_df = depth_df.sort_values(by=["val_auprc", "val_recall", "val_precision"], ascending=[False, False, False])
depth_df

,val_log_loss,val_precision,val_recall,val_auprc,val_roc_auc,model,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features
3,0.003525,0.935897,0.744898,0.806093,0.977554,"(DecisionTreeClassifier(max_depth=20, max_feat...",200,20.0,2,1,sqrt
2,0.003197,0.935897,0.744898,0.803791,0.983157,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15.0,2,1,sqrt
0,0.009009,0.936709,0.755102,0.802752,0.935856,"(DecisionTreeClassifier(max_features='sqrt', r...",200,NaN,2,1,sqrt
1,0.003300,0.935897,0.744898,0.796548,0.979216,"(DecisionTreeClassifier(max_depth=10, max_feat...",200,10.0,2,1,sqrt

In [25]:
best_depth = 15
print("BEST max_depth:", best_depth)
base_params["max_depth"] = best_depth

BEST max_depth: 15

auprc상 제일 높은 성능을 보인건 깊이가 20인 모델이였으나 사기 탐지에서 가장 중요한 지표인 recall과 precision은 깊이가 20인 모델과 깊이가 15인 모델이 값이 동일하고 auprc외의 다른 지표상에서는 깊이가 15인 모델이 더 좋은 성능을 보이기도 하였으므로 모델의 복잡도 증가량에 비해 성능 개선이 미미하다고 판단하여 best_depth는 15로 결정하였다.

In [26]:
split_candidates = [2, 5, 10]

split_results = []

for split in split_candidates:
    params = base_params.copy()
    params["min_samples_split"] = split
    
    metrics = eval_rf(params, X_train, y_train, X_val, y_val)
    metrics.update(params)
    split_results.append(metrics)

split_df = pd.DataFrame(split_results)
split_df = split_df.sort_values(by=["val_auprc", "val_recall", "val_precision"], ascending=[False, False, False])
split_df

,val_log_loss,val_precision,val_recall,val_auprc,val_roc_auc,model,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features
0,0.003197,0.935897,0.744898,0.803791,0.983157,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,1,sqrt
1,0.003320,0.935897,0.744898,0.794288,0.977519,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,5,1,sqrt
2,0.003458,0.935897,0.744898,0.791637,0.979338,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,10,1,sqrt

In [27]:
best_split = int(split_df.iloc[0]["min_samples_split"])
print("BEST min_samples_split:", best_split)

base_params["min_samples_split"] = best_split

BEST min_samples_split: 2

In [28]:
leaf_candidates = [1, 2, 4]

leaf_results = []

for leaf in leaf_candidates:
    params = base_params.copy()
    params["min_samples_leaf"] = leaf
    
    metrics = eval_rf(params, X_train, y_train, X_val, y_val)
    metrics.update(params)
    leaf_results.append(metrics)

leaf_df = pd.DataFrame(leaf_results)
leaf_df = leaf_df.sort_values(by=["val_auprc", "val_recall", "val_precision"], ascending=[False, False, False])
leaf_df

,val_log_loss,val_precision,val_recall,val_auprc,val_roc_auc,model,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features
0,0.003197,0.935897,0.744898,0.803791,0.983157,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,1,sqrt
1,0.003296,0.935897,0.744898,0.802598,0.978374,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,2,sqrt
2,0.003460,0.924051,0.744898,0.792160,0.980415,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,4,sqrt

In [29]:
best_leaf = int(leaf_df.iloc[0]["min_samples_leaf"])
print("BEST min_samples_leaf:", best_leaf)

base_params["min_samples_leaf"] = best_leaf

BEST min_samples_leaf: 1

In [30]:
feat_candidates = ["sqrt", "log2"]

feat_results = []

for feat in feat_candidates:
    params = base_params.copy()
    params["max_features"] = feat
    
    metrics = eval_rf(params, X_train, y_train, X_val, y_val)
    metrics.update(params)
    feat_results.append(metrics)

feat_df = pd.DataFrame(feat_results)
feat_df = feat_df.sort_values(by=["val_auprc", "val_recall", "val_precision"], ascending=[False, False, False])
feat_df

,val_log_loss,val_precision,val_recall,val_auprc,val_roc_auc,model,n_estimators,max_depth,min_samples_split,min_samples_leaf,max_features
0,0.003197,0.935897,0.744898,0.803791,0.983157,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,1,sqrt
1,0.003323,0.935065,0.734694,0.802432,0.979998,"(DecisionTreeClassifier(max_depth=15, max_feat...",200,15,2,1,log2

In [32]:
best_feat = feat_df.iloc[0]["max_features"]
print("BEST max_features:", best_feat)

base_params["max_features"] = best_feat

BEST max_features: sqrt

In [33]:
print(f'최고 성능 파라메터 : {base_params}')

최고 성능 파라메터 : {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}

In [34]:
# train + val 합치기
X_train_final = pd.concat([X_train, X_val], axis=0)
y_train_final = pd.concat([y_train, y_val], axis=0)

final_model = RandomForestClassifier(
    **base_params,
    random_state=42,
    n_jobs=-1
)

final_model.fit(X_train_final, y_train_final)

# test 평가
y_test_prob = final_model.predict_proba(X_test)[:, 1]
y_test_pred = (y_test_prob >= 0.5).astype(int)

test_loss = log_loss(y_test, y_test_prob)
test_prec = precision_score(y_test, y_test_pred, zero_division=0)
test_rec = recall_score(y_test, y_test_pred, zero_division=0)
test_auprc = average_precision_score(y_test, y_test_prob)
test_roc_auc = roc_auc_score(y_test, y_test_prob)

print("=== FINAL TEST METRICS (threshold = 0.5) ===")
print(f"log_loss   : {test_loss:.4f}")
print(f"precision  : {test_prec:.4f}")
print(f"recall     : {test_rec:.4f}")
print(f"AUPRC      : {test_auprc:.4f}")
print(f"ROC-AUC    : {test_roc_auc:.4f}")
print("BEST PARAMS:", base_params)

=== FINAL TEST METRICS (threshold = 0.5) ===
log_loss   : 0.0025
precision  : 0.9643
recall     : 0.8182
AUPRC      : 0.8766
ROC-AUC    : 0.9760
BEST PARAMS: {'n_estimators': 200, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt'}